name: QEMU

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:

permissions:
  contents: read

jobs:
  integration:
    name: Integration tests
    strategy:
      fail-fast: false
      matrix:
        # We run on standard arm64 runners since this test is very quick.
        platform:
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 1
      - name: Show host info
        run: |
          uname -a
          sw_vers
          ifconfig
      - name: Build
        run: |
          make
          sudo make install
      - name: Print launchd status (shared mode)
        run: launchctl print system/io.github.lima-vm.socket_vmnet
      - name: Fetch homebrew-core commit messages
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          # needed by ./hack/brew-install-version.sh
          repository: homebrew/homebrew-core
          path: homebrew-core
          fetch-depth: 0
          filter: tree:0
      - name: Install test dependencies
        run: |
          brew install bash coreutils
          # QEMU 9.1.0 seems to break on GitHub runners, both on Monterey and Ventura
          # We revert back to 8.2.1, which seems to work fine
          ./hack/brew-install-version.sh qemu 8.2.1
      - name: Test (shared mode)
        run: ./test/test.sh /var/run/socket_vmnet
      # Bridged mode cannot be tested on GHA
